// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/nvidia component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nvidia")
	ScopeName = "github.com/pierre-prevoteau/otel-receiver-nvidia/nvidiareceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
