// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NvidiaGpuMemoryFree: NvidiaGpuMemoryFreeMetricConfig{
						Enabled: true,
					},
					NvidiaGpuMemoryTotal: NvidiaGpuMemoryTotalMetricConfig{
						Enabled: true,
					},
					NvidiaGpuMemoryUsed: NvidiaGpuMemoryUsedMetricConfig{
						Enabled: true,
					},
					NvidiaGpuMemoryUtilization: NvidiaGpuMemoryUtilizationMetricConfig{
						Enabled: true,
					},
					NvidiaGpuUtilization: NvidiaGpuUtilizationMetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					NvidiaGpuIndex: ResourceAttributeConfig{Enabled: true},
					NvidiaGpuName:  ResourceAttributeConfig{Enabled: true},
					NvidiaGpuUUID:  ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NvidiaGpuMemoryFree: NvidiaGpuMemoryFreeMetricConfig{
						Enabled: false,
					},
					NvidiaGpuMemoryTotal: NvidiaGpuMemoryTotalMetricConfig{
						Enabled: false,
					},
					NvidiaGpuMemoryUsed: NvidiaGpuMemoryUsedMetricConfig{
						Enabled: false,
					},
					NvidiaGpuMemoryUtilization: NvidiaGpuMemoryUtilizationMetricConfig{
						Enabled: false,
					},
					NvidiaGpuUtilization: NvidiaGpuUtilizationMetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					NvidiaGpuIndex: ResourceAttributeConfig{Enabled: false},
					NvidiaGpuName:  ResourceAttributeConfig{Enabled: false},
					NvidiaGpuUUID:  ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(NvidiaGpuMemoryFreeMetricConfig{}, NvidiaGpuMemoryTotalMetricConfig{}, NvidiaGpuMemoryUsedMetricConfig{}, NvidiaGpuMemoryUtilizationMetricConfig{}, NvidiaGpuUtilizationMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				NvidiaGpuIndex: ResourceAttributeConfig{Enabled: true},
				NvidiaGpuName:  ResourceAttributeConfig{Enabled: true},
				NvidiaGpuUUID:  ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				NvidiaGpuIndex: ResourceAttributeConfig{Enabled: false},
				NvidiaGpuName:  ResourceAttributeConfig{Enabled: false},
				NvidiaGpuUUID:  ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
