// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// NvidiaGpuMemoryFreeMetricConfig provides config for the nvidia.gpu.memory.free metric.
type NvidiaGpuMemoryFreeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NvidiaGpuMemoryFreeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NvidiaGpuMemoryTotalMetricConfig provides config for the nvidia.gpu.memory.total metric.
type NvidiaGpuMemoryTotalMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NvidiaGpuMemoryTotalMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NvidiaGpuMemoryUsedMetricConfig provides config for the nvidia.gpu.memory.used metric.
type NvidiaGpuMemoryUsedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NvidiaGpuMemoryUsedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NvidiaGpuMemoryUtilizationMetricConfig provides config for the nvidia.gpu.memory.utilization metric.
type NvidiaGpuMemoryUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NvidiaGpuMemoryUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NvidiaGpuUtilizationMetricConfig provides config for the nvidia.gpu.utilization metric.
type NvidiaGpuUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NvidiaGpuUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for nvidia metrics.
type MetricsConfig struct {
	NvidiaGpuMemoryFree        NvidiaGpuMemoryFreeMetricConfig        `mapstructure:"nvidia.gpu.memory.free"`
	NvidiaGpuMemoryTotal       NvidiaGpuMemoryTotalMetricConfig       `mapstructure:"nvidia.gpu.memory.total"`
	NvidiaGpuMemoryUsed        NvidiaGpuMemoryUsedMetricConfig        `mapstructure:"nvidia.gpu.memory.used"`
	NvidiaGpuMemoryUtilization NvidiaGpuMemoryUtilizationMetricConfig `mapstructure:"nvidia.gpu.memory.utilization"`
	NvidiaGpuUtilization       NvidiaGpuUtilizationMetricConfig       `mapstructure:"nvidia.gpu.utilization"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NvidiaGpuMemoryFree: NvidiaGpuMemoryFreeMetricConfig{
			Enabled: true,
		},
		NvidiaGpuMemoryTotal: NvidiaGpuMemoryTotalMetricConfig{
			Enabled: true,
		},
		NvidiaGpuMemoryUsed: NvidiaGpuMemoryUsedMetricConfig{
			Enabled: true,
		},
		NvidiaGpuMemoryUtilization: NvidiaGpuMemoryUtilizationMetricConfig{
			Enabled: true,
		},
		NvidiaGpuUtilization: NvidiaGpuUtilizationMetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for nvidia resource attributes.
type ResourceAttributesConfig struct {
	NvidiaGpuIndex ResourceAttributeConfig `mapstructure:"nvidia.gpu.index"`
	NvidiaGpuName  ResourceAttributeConfig `mapstructure:"nvidia.gpu.name"`
	NvidiaGpuUUID  ResourceAttributeConfig `mapstructure:"nvidia.gpu.uuid"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		NvidiaGpuIndex: ResourceAttributeConfig{
			Enabled: true,
		},
		NvidiaGpuName: ResourceAttributeConfig{
			Enabled: true,
		},
		NvidiaGpuUUID: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for nvidia metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
