// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetNvidiaGpuIndex("nvidia.gpu.index-val")
			rb.SetNvidiaGpuName("nvidia.gpu.name-val")
			rb.SetNvidiaGpuUUID("nvidia.gpu.uuid-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 3, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 3, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}
			nvidiaGpuIndexAttrVal, ok := res.Attributes().Get("nvidia.gpu.index")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nvidia.gpu.index-val", nvidiaGpuIndexAttrVal.Str())
			}
			nvidiaGpuNameAttrVal, ok := res.Attributes().Get("nvidia.gpu.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nvidia.gpu.name-val", nvidiaGpuNameAttrVal.Str())
			}
			nvidiaGpuUUIDAttrVal, ok := res.Attributes().Get("nvidia.gpu.uuid")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "nvidia.gpu.uuid-val", nvidiaGpuUUIDAttrVal.Str())
			}
		})
	}
}
