// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetNvidiaGpuIndex sets provided value as "nvidia.gpu.index" attribute.
func (rb *ResourceBuilder) SetNvidiaGpuIndex(val string) {
	if rb.config.NvidiaGpuIndex.Enabled {
		rb.res.Attributes().PutStr("nvidia.gpu.index", val)
	}
}

// SetNvidiaGpuName sets provided value as "nvidia.gpu.name" attribute.
func (rb *ResourceBuilder) SetNvidiaGpuName(val string) {
	if rb.config.NvidiaGpuName.Enabled {
		rb.res.Attributes().PutStr("nvidia.gpu.name", val)
	}
}

// SetNvidiaGpuUUID sets provided value as "nvidia.gpu.uuid" attribute.
func (rb *ResourceBuilder) SetNvidiaGpuUUID(val string) {
	if rb.config.NvidiaGpuUUID.Enabled {
		rb.res.Attributes().PutStr("nvidia.gpu.uuid", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
